"""
AI Image Classifier — Model Inference Engine
Handles CLIP zero-shot classification with prompt ensembling and test-time augmentation.
"""

import os
import io
import torch
import torch.nn.functional as F
import open_clip
from PIL import Image

# PyTorch 2.6+ compatibility for TorchScript weights
_orig_load = torch.load
torch.load = lambda *args, **kwargs: _orig_load(*args, **{**kwargs, 'weights_only': False})

CLIP_MODEL_NAME = "ViT-B-32"
CLIP_PRETRAINED = "openai"
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

AI_PROMPTS = [
    "an image generated by artificial intelligence",
    "a synthetic computer-generated image",
    "a deepfake or AI-generated picture",
    "an artificially created digital artwork by AI",
    "a fake image produced by a neural network",
    "an AI-rendered synthetic photograph",
    "a machine-generated artificial image",
    "an image created by stable diffusion, midjourney, or dall-e",
    "a digitally fabricated image with unnatural perfection",
    "a generative AI output image",
]

REAL_PROMPTS = [
    "a real photograph captured by a camera",
    "an authentic unedited photograph",
    "a genuine real-world photograph",
    "a natural photo taken in real life",
    "an original photograph from a digital camera",
    "a real candid photograph of the real world",
    "a genuine untouched photo from a camera sensor",
    "a real image of the natural world",
    "a raw photograph with natural lighting and imperfections",
    "an unmanipulated authentic camera photo",
]

clip_model = None
clip_preprocess = None
class_embeddings = None


def load_model():
    """Load the CLIP model and pre-compute text embeddings for zero-shot classification."""
    global clip_model, clip_preprocess, class_embeddings

    if clip_model is not None:
        return

    # Check root directory or cache for ViT-B-32.pt
    base_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
    model_file = os.path.join(base_dir, "ViT-B-32.pt")
    
    if not os.path.exists(model_file):
        cache_file = os.path.expanduser("~/.cache/clip/ViT-B-32.pt")
        if os.path.exists(cache_file):
            model_file = cache_file
        else:
            try:
                from .download_model import download_file
                model_file = download_file()
            except Exception as e:
                print(f"[!] Downloader warning: {e}, using pretrained tag", flush=True)
                model_file = CLIP_PRETRAINED

    print(f"[*] Loading CLIP model: {CLIP_MODEL_NAME} from {model_file}...", flush=True)
    print(f"[*] Device: {DEVICE}", flush=True)

    clip_model, _, clip_preprocess = open_clip.create_model_and_transforms(
        CLIP_MODEL_NAME, pretrained=model_file, device=DEVICE
    )
    tokenizer = open_clip.get_tokenizer(CLIP_MODEL_NAME)
    clip_model.eval()

    with torch.no_grad():
        ai_tokens = tokenizer(AI_PROMPTS).to(DEVICE)
        ai_features = clip_model.encode_text(ai_tokens)
        ai_features = F.normalize(ai_features, dim=-1)
        ai_centroid = F.normalize(ai_features.mean(dim=0, keepdim=True), dim=-1)

        real_tokens = tokenizer(REAL_PROMPTS).to(DEVICE)
        real_features = clip_model.encode_text(real_tokens)
        real_features = F.normalize(real_features, dim=-1)
        real_centroid = F.normalize(real_features.mean(dim=0, keepdim=True), dim=-1)

        class_embeddings = torch.cat([ai_centroid, real_centroid], dim=0)

    print(f"[+] CLIP model loaded successfully ({len(AI_PROMPTS)} AI + {len(REAL_PROMPTS)} Real prompts)", flush=True)


def classify_image(image_bytes: bytes) -> dict:
    """
    Classify an image as AI-Generated or Real using CLIP zero-shot classification
    with test-time augmentation (original + horizontal flip).
    """
    if clip_model is None:
        load_model()

    img = Image.open(io.BytesIO(image_bytes)).convert("RGB")
    img_flipped = img.transpose(Image.FLIP_LEFT_RIGHT)
    augmented_images = [img, img_flipped]

    all_probs = []
    with torch.no_grad():
        for aug_img in augmented_images:
            img_tensor = clip_preprocess(aug_img).unsqueeze(0).to(DEVICE)
            image_features = clip_model.encode_image(img_tensor)
            image_features = F.normalize(image_features, dim=-1)

            logit_scale = clip_model.logit_scale.exp()
            logits = logit_scale * (image_features @ class_embeddings.T)
            probs = F.softmax(logits, dim=-1).squeeze(0)
            all_probs.append(probs)

    avg_probs = torch.stack(all_probs).mean(dim=0)
    ai_prob = avg_probs[0].item()
    real_prob = avg_probs[1].item()

    if ai_prob > real_prob:
        label = "AI-Generated"
        confidence = ai_prob * 100
    else:
        label = "Real"
        confidence = real_prob * 100

    return {
        "label": label,
        "confidence": round(confidence, 1),
        "ai_score": round(ai_prob * 100, 1),
        "real_score": round(real_prob * 100, 1),
    }
